from __future__ import annotations

import sys
from pathlib import Path


def replace_exact(path: Path, old: str, new: str) -> None:
    text = path.read_text(encoding="utf-8")
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"expected exactly one replacement in {path}, found {count}")
    path.write_text(text.replace(old, new), encoding="utf-8")


def main(root: Path) -> None:
    core = root / "src/medscale/mesc/_mrl_0801_hf_acquisition_v1.py"
    cli = root / "scripts/mesc_mrl_0801_hf_acquire.py"
    spec = root / "specs/mesc-experiment-0/mrl-0801-hf-acquisition-provenance-v1.md"

    replace_exact(
        core,
        '''def _probe_atomic_descriptor_publication(*, root_fd: int) -> None:\n    """Prove atomic publication on the same filesystem without deleting probe namespace."""\n    parent_fd: int | None = None\n    source_fd: int | None = None\n    try:\n        parent_fd = os.open(\n            "..",\n            os.O_RDONLY | _O_DIRECTORY | _O_NOFOLLOW | _O_CLOEXEC,\n            dir_fd=root_fd,\n        )\n        root_observation = os.fstat(root_fd)\n        parent_observation = os.fstat(parent_fd)\n        if not stat.S_ISDIR(parent_observation.st_mode):\n            raise MRL0801HfAcquisitionError(\n                "atomic publication witness parent is not a directory"\n            )\n        if parent_observation.st_dev != root_observation.st_dev:\n            raise MRL0801HfAcquisitionError(\n                "safe same-filesystem atomic publication witness is unavailable"\n            )\n        source_fd = _open_unnamed_temp_file(root_fd=parent_fd)\n        source = os.fstat(source_fd)\n        if not stat.S_ISREG(source.st_mode):\n            raise MRL0801HfAcquisitionError(\n                "atomic publication witness did not create a regular file"\n            )\n        witness_name = f".mrl-0801-publication-witness-{secrets.token_hex(16)}"\n        _publish_open_descriptor_no_replace(\n            source_fd=source_fd,\n            root_fd=parent_fd,\n            target_name=witness_name,\n        )\n        linked = _descriptor_entry_stat(root_fd=parent_fd, name=witness_name)\n        if (\n            linked is None\n            or not stat.S_ISREG(linked.st_mode)\n            or _stat_descriptor_identity(linked) != _stat_descriptor_identity(source)\n        ):\n            raise MRL0801HfAcquisitionError(\n                "atomic publication witness produced an invalid identity"\n            )\n    except MRL0801HfAcquisitionError:\n        raise\n    except OSError:\n        raise MRL0801HfAcquisitionError(\n            "atomic descriptor publication capability witness failed safely"\n        ) from None\n    finally:\n        if source_fd is not None:\n            os.close(source_fd)\n        if parent_fd is not None:\n            os.close(parent_fd)\n''',
        '''def _probe_atomic_descriptor_publication(*, root_fd: int) -> None:\n    """Prove atomic publication, retain the witness, and block before remote access."""\n    source_fd: int | None = None\n    try:\n        source_fd = _open_unnamed_temp_file(root_fd=root_fd)\n        source = os.fstat(source_fd)\n        if not stat.S_ISREG(source.st_mode):\n            raise MRL0801HfAcquisitionError(\n                "atomic publication witness did not create a regular file"\n            )\n        witness_name = f".mrl-0801-publication-witness-{secrets.token_hex(16)}"\n        _publish_open_descriptor_no_replace(\n            source_fd=source_fd,\n            root_fd=root_fd,\n            target_name=witness_name,\n        )\n        linked = _descriptor_entry_stat(root_fd=root_fd, name=witness_name)\n        if (\n            linked is None\n            or not stat.S_ISREG(linked.st_mode)\n            or _stat_descriptor_identity(linked) != _stat_descriptor_identity(source)\n        ):\n            raise MRL0801HfAcquisitionError(\n                "atomic publication witness produced an invalid identity"\n            )\n        raise MRL0801HfAcquisitionError(\n            "atomic publication capability proven; witness retained because safe atomic "\n            "cleanup is unavailable, so remote access is blocked"\n        )\n    except MRL0801HfAcquisitionError:\n        raise\n    except OSError:\n        raise MRL0801HfAcquisitionError(\n            "atomic descriptor publication capability witness failed safely"\n        ) from None\n    finally:\n        if source_fd is not None:\n            os.close(source_fd)\n''',
    )

    replace_exact(
        cli,
        '''def _probe_receipt_atomic_publication(output: _BoundReceiptOutput) -> None:\n    """Prove receipt publication on the same filesystem without deleting probe namespace."""\n    _require_bound_output_parent_identity(output)\n    witness_parent_fd: int | None = None\n    source_fd: int | None = None\n    try:\n        witness_parent_fd = os.open(\n            "..",\n            os.O_RDONLY | _O_DIRECTORY | _O_NOFOLLOW | _O_CLOEXEC,\n            dir_fd=output.descriptor,\n        )\n        output_parent = os.fstat(output.descriptor)\n        witness_parent = os.fstat(witness_parent_fd)\n        if not stat.S_ISDIR(witness_parent.st_mode):\n            raise AcquisitionEntrypointError(\n                "atomic receipt publication witness parent is not a directory"\n            )\n        if witness_parent.st_dev != output_parent.st_dev:\n            raise AcquisitionEntrypointError(\n                "safe same-filesystem receipt publication witness is unavailable"\n            )\n        try:\n            source_fd = os.open(\n                ".",\n                os.O_WRONLY | _O_TMPFILE | _O_CLOEXEC,\n                0o600,\n                dir_fd=witness_parent_fd,\n            )\n        except OSError:\n            raise AcquisitionEntrypointError(\n                "unnamed receipt publication is unsupported on this filesystem"\n            ) from None\n        source = os.fstat(source_fd)\n        if not stat.S_ISREG(source.st_mode):\n            raise AcquisitionEntrypointError(\n                "atomic receipt publication witness did not create a regular file"\n            )\n        witness_name = f".mrl-0801-receipt-witness-{secrets.token_hex(16)}"\n        witness_output = _BoundReceiptOutput(\n            path=output.parent_path.parent / witness_name,\n            parent_path=output.parent_path.parent,\n            descriptor=witness_parent_fd,\n            device=witness_parent.st_dev,\n            inode=witness_parent.st_ino,\n            name=witness_name,\n        )\n        _publish_open_descriptor_no_replace(source_fd=source_fd, output=witness_output)\n        linked = _descriptor_output_stat(witness_output)\n        if (\n            linked is None\n            or not stat.S_ISREG(linked.st_mode)\n            or _stat_identity(linked) != _stat_identity(source)\n        ):\n            raise AcquisitionEntrypointError(\n                "atomic receipt publication witness produced an invalid identity"\n            )\n        _require_bound_output_parent_identity(output)\n    except AcquisitionEntrypointError:\n        raise\n    except OSError:\n        raise AcquisitionEntrypointError(\n            "atomic receipt publication capability witness failed safely"\n        ) from None\n    finally:\n        if source_fd is not None:\n            os.close(source_fd)\n        if witness_parent_fd is not None:\n            os.close(witness_parent_fd)\n''',
        '''def _probe_receipt_atomic_publication(output: _BoundReceiptOutput) -> None:\n    """Prove receipt publication, retain the witness, and block before acquisition."""\n    _require_bound_output_parent_identity(output)\n    source_fd: int | None = None\n    try:\n        try:\n            source_fd = os.open(\n                ".",\n                os.O_WRONLY | _O_TMPFILE | _O_CLOEXEC,\n                0o600,\n                dir_fd=output.descriptor,\n            )\n        except OSError:\n            raise AcquisitionEntrypointError(\n                "unnamed receipt publication is unsupported on this filesystem"\n            ) from None\n        source = os.fstat(source_fd)\n        if not stat.S_ISREG(source.st_mode):\n            raise AcquisitionEntrypointError(\n                "atomic receipt publication witness did not create a regular file"\n            )\n        witness_name = f".mrl-0801-receipt-witness-{secrets.token_hex(16)}"\n        witness_output = _BoundReceiptOutput(\n            path=output.parent_path / witness_name,\n            parent_path=output.parent_path,\n            descriptor=output.descriptor,\n            device=output.device,\n            inode=output.inode,\n            name=witness_name,\n        )\n        _publish_open_descriptor_no_replace(source_fd=source_fd, output=witness_output)\n        linked = _descriptor_output_stat(witness_output)\n        if (\n            linked is None\n            or not stat.S_ISREG(linked.st_mode)\n            or _stat_identity(linked) != _stat_identity(source)\n        ):\n            raise AcquisitionEntrypointError(\n                "atomic receipt publication witness produced an invalid identity"\n            )\n        _require_bound_output_parent_identity(output)\n        raise AcquisitionEntrypointError(\n            "atomic receipt publication capability proven; witness retained because safe "\n            "atomic cleanup is unavailable, so acquisition is blocked"\n        )\n    except AcquisitionEntrypointError:\n        raise\n    except OSError:\n        raise AcquisitionEntrypointError(\n            "atomic receipt publication capability witness failed safely"\n        ) from None\n    finally:\n        if source_fd is not None:\n            os.close(source_fd)\n''',
    )

    replace_exact(
        spec,
        "Before any remote metadata request or model byte download, the executor must first prove that unnamed-file atomic publication actually works on the bound destination filesystem. The CLI performs the same proof for each bound receipt-parent filesystem before acquisition begins. A successful `O_TMPFILE` open or an exported `linkat` symbol alone is insufficient. The capability check must successfully publish an unnamed file with `linkat(..., AT_EMPTY_PATH)` into the descriptor-opened parent on the same device and verify the linked identity. The zero-byte hidden capability witness is intentionally retained; automatic witness unlink or directory removal is prohibited because namespace deletion cannot be bound atomically to a previously observed inode.\n",
        "Before any remote metadata request or model byte download, the executor must first prove that unnamed-file atomic publication actually works on the bound destination filesystem. The CLI performs the same proof for each bound receipt-parent filesystem before acquisition begins. A successful `O_TMPFILE` open or an exported `linkat` symbol alone is insufficient. The capability check publishes an unnamed file with `linkat(..., AT_EMPTY_PATH)` directly into the already-bound transaction directory and verifies the linked identity. Because V1 has no kernel primitive that atomically binds a prior inode observation to namespace removal, the zero-byte hidden capability witness is intentionally retained and the operation then fails closed before remote metadata access or acquisition.\n",
    )
    replace_exact(
        spec,
        "The executor never overwrites existing asset files. Before any remote metadata request, it opens the destination's actual parent through descriptor-relative `..`, requires the parent to be on the same device, creates an unnamed `O_TMPFILE` there, publishes a random hidden zero-byte witness with `linkat(..., AT_EMPTY_PATH)`, verifies the linked inode identity, and retains that witness rather than performing a racy namespace deletion. Every authorized file is then streamed into an unnamed same-filesystem `O_TMPFILE` opened through the bound destination descriptor, fully hashed and size-checked, then atomically published from that still-open file descriptor with `linkat(..., AT_EMPTY_PATH)`. If the primitive or filesystem support is unavailable, acquisition fails closed before network access. If a racing target appears, the atomic link fails without modifying that target. Before publication, failure cleanup is descriptor close only because the temporary file has no directory entry.\n",
        "The executor never overwrites existing asset files. Before any remote metadata request, it creates an unnamed `O_TMPFILE` through the already-bound destination descriptor, publishes a random hidden zero-byte witness with `linkat(..., AT_EMPTY_PATH)`, verifies the linked inode identity, retains the witness, and returns `BLOCKED` before network access because safe atomic witness cleanup is unavailable in V1. This proves the required publication primitive without performing a racy namespace deletion or redirecting publication through a mutable parent relationship. The model-byte streaming path remains implemented for a future separately qualified execution boundary, but this V1 gate does not reach it after a successful capability proof.\n",
    )
    replace_exact(
        spec,
        "Receipt publication by the CLI is supplied as the acquisition transaction finalizer and uses the same unnamed-file pattern in each pre-bound external receipt parent. Before acquisition begins, every bound receipt parent opens its actual parent through descriptor-relative `..`, requires the same device, and leaves an independently verified hidden zero-byte publication witness there. No capability-witness cleanup is automatic. Receipt bytes are written and fsynced before one atomic descriptor publication to the final name. The CLI performs no automatic receipt unlink cleanup.\n",
        "Receipt publication by the CLI uses the same unnamed-file pattern in each pre-bound external receipt parent. Before acquisition begins, the bound receipt-parent descriptor publishes and verifies its own hidden zero-byte witness, retains it, and returns `BLOCKED`; no receipt bytes, model bytes, or remote metadata are reached through this V1 path after a successful proof. No capability-witness cleanup is automatic because a later name deletion cannot be proven to remove the previously verified inode atomically.\n",
    )


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: pr390_failclosed_witness_patcher.py <repo-root>")
    main(Path(sys.argv[1]))
